version: 2

updates:
- package-ecosystem: bundler
  directory: "/"
  insecure-external-code-execution: allow
  schedule:
    interval: daily
    time: "06:00"
    timezone: Etc/UCT
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
