version: '3'

services:
    web:
        build:
            context: .
            args:
                - JFROG_USERNAME
                - JFROG_PASSWORD
        depends_on:
            - db
        ports:
            - '3000:3000'
        env_file:
            - .env
        volumes:
            - .:/var/app
        # environment:
        #     REDIS_URL: redis://redis:6379
    db:
        image: postgres:13.4-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
    # redis:
    #     image: redis:3.0.3
    #     expose:
    #         - "6379"
    #     volumes:
    #         - redis:/data
volumes:
    postgres13:
    # redis:
