version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4
  
jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.2-node
        environment:
          COVERAGE: 'true'
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/tech-interview-challenge_tests
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: tech-interview-challenge_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Set up DB
          command: |
            bundle exec rails db:create --trace
            bundle exec rails db:migrate
      - run: ./cc-test-reporter before-build
      - run: bundle exec rspec --profile 10

workflows:
  all-tests:
    jobs:
      - test