commonLabels:
  appProject: tech-interview-challenge
  alertGroup: group:default/devtools
  version: staging
  team: group:default/devtools

secrets:
  useSecret: true
  name: tech-interview-challenge

applications:
  - name: tech-interview-challenge
    kind: deployment
    namespace: "devexp"
    labels:
      appGroup: web
    containerPort: 3000
    service:
      enabled: true
    ingressEnabled: true
    ingressInternal: true
    ingress:
      prefix: tech-interview-challenge
      domain: staging.rdops.systems
    resources:
      limits:
        cpu: 800m
        memory: 1024Mi
      requests:
        cpu: 400m
        memory: 512Mi
    autoscaling:
      enabled: false
    replicaCount: 3
